server.port: 30003

eureka:
  instance:
    hostname: peer3
    instance-id: earthshaker-30003
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:30001/eureka,http://${spring.security.user.name}:${spring.security.user.password}@peer2:30002/eureka

logging.level.root: info