spring:
  application:
    name: earthshaker
  security:
    user:
      name: root
      password: 123456

server.port: 30002

eureka:
  instance:
    hostname: peer2
    instance-id: earthshaker-30002
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:30001/eureka,http://${spring.security.user.name}:${spring.security.user.password}@peer3:30003/eureka

logging.level.root: info